// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyMatters.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyMatters.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201025906_CompleteSchemaInitial")]
    partial class CompleteSchemaInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyMatters.Core.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Domain")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IncludeInForecast")
                        .HasColumnType("boolean");

                    b.Property<string>("Institution")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("SafeMinimumBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Domain")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedBillId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedGoalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedIncomeStreamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SnoozedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RelatedAccountId");

                    b.HasIndex("RelatedBillId");

                    b.HasIndex("RelatedGoalId");

                    b.HasIndex("RelatedIncomeStreamId");

                    b.HasIndex("Severity");

                    b.HasIndex("State");

                    b.HasIndex("TriggeredAt")
                        .IsDescending();

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DefaultAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Domain")
                        .HasColumnType("integer");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAutoPay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DefaultAccountId");

                    b.HasIndex("Domain");

                    b.HasIndex("IsActive");

                    b.HasIndex("NextDueDate");

                    b.HasIndex("UserId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.ForecastSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Domain")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ForecastData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("integer");

                    b.Property<int?>("RunwayDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Domain", "HorizonDays", "GeneratedAt")
                        .IsDescending(false, false, false, true);

                    b.ToTable("ForecastSnapshots");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Domain")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FixedContributionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FundingStrategy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("PercentOfIncome")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("IsActive");

                    b.HasIndex("TargetDate");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.GoalAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GoalId");

                    b.HasIndex("GoalId", "AccountId")
                        .IsUnique();

                    b.ToTable("GoalAccounts");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.IncomeStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Domain")
                        .HasColumnType("integer");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LastReceivedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NextExpectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextExpectedWindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextExpectedWindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("TypicalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Domain");

                    b.HasIndex("IsActive");

                    b.HasIndex("NextExpectedDate");

                    b.HasIndex("UserId");

                    b.ToTable("IncomeStreams");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SettingKey")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncomeStreamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedMerchant")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("TransferAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("GoalId");

                    b.HasIndex("IncomeStreamId");

                    b.HasIndex("TransferAccountId");

                    b.HasIndex("AccountId", "Date")
                        .IsDescending(false, true);

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultForecastHorizonDays")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Account", b =>
                {
                    b.HasOne("MoneyMatters.Core.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Alert", b =>
                {
                    b.HasOne("MoneyMatters.Core.Entities.Account", "RelatedAccount")
                        .WithMany()
                        .HasForeignKey("RelatedAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMatters.Core.Entities.Bill", "RelatedBill")
                        .WithMany()
                        .HasForeignKey("RelatedBillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMatters.Core.Entities.Goal", "RelatedGoal")
                        .WithMany()
                        .HasForeignKey("RelatedGoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMatters.Core.Entities.IncomeStream", "RelatedIncomeStream")
                        .WithMany()
                        .HasForeignKey("RelatedIncomeStreamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMatters.Core.Entities.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedAccount");

                    b.Navigation("RelatedBill");

                    b.Navigation("RelatedGoal");

                    b.Navigation("RelatedIncomeStream");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Bill", b =>
                {
                    b.HasOne("MoneyMatters.Core.Entities.Account", "DefaultAccount")
                        .WithMany("Bills")
                        .HasForeignKey("DefaultAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMatters.Core.Entities.User", "User")
                        .WithMany("Bills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.ForecastSnapshot", b =>
                {
                    b.HasOne("MoneyMatters.Core.Entities.User", "User")
                        .WithMany("ForecastSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Goal", b =>
                {
                    b.HasOne("MoneyMatters.Core.Entities.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.GoalAccount", b =>
                {
                    b.HasOne("MoneyMatters.Core.Entities.Account", "Account")
                        .WithMany("GoalAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMatters.Core.Entities.Goal", "Goal")
                        .WithMany("GoalAccounts")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.IncomeStream", b =>
                {
                    b.HasOne("MoneyMatters.Core.Entities.Account", "Account")
                        .WithMany("IncomeStreams")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMatters.Core.Entities.User", "User")
                        .WithMany("IncomeStreams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Setting", b =>
                {
                    b.HasOne("MoneyMatters.Core.Entities.User", "User")
                        .WithMany("Settings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Transaction", b =>
                {
                    b.HasOne("MoneyMatters.Core.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyMatters.Core.Entities.Bill", "Bill")
                        .WithMany("Transactions")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMatters.Core.Entities.Goal", "Goal")
                        .WithMany("Transactions")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMatters.Core.Entities.IncomeStream", "IncomeStream")
                        .WithMany("Transactions")
                        .HasForeignKey("IncomeStreamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyMatters.Core.Entities.Account", "TransferAccount")
                        .WithMany()
                        .HasForeignKey("TransferAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Bill");

                    b.Navigation("Goal");

                    b.Navigation("IncomeStream");

                    b.Navigation("TransferAccount");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Account", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("GoalAccounts");

                    b.Navigation("IncomeStreams");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Bill", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.Goal", b =>
                {
                    b.Navigation("GoalAccounts");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.IncomeStream", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyMatters.Core.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Alerts");

                    b.Navigation("Bills");

                    b.Navigation("ForecastSnapshots");

                    b.Navigation("Goals");

                    b.Navigation("IncomeStreams");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
